libname ACTIVE "C:\Users\trb5511\Box\Tyler's Folder\Papers\Pain and Cognition - ACTIVE\ACTIVE\Data\Final SAS Data";
ods pdf file = "C:\Users\trb5511\Box\Tyler's Folder\Papers\Pain and Cognition - ACTIVE\ACTIVE\Preliminary Analysis\Output\ConditionalGrowthModel_09252019.pdf";
Title "Conditional Growth Models"; 
PROC MIXED data=ACTIVE.step15long method=reml noclprint covtest noitprint; 
class id men rerace(ref="0") married (ref="1");
where intgrpR = 4; 
model  MMSE = reage educlevl men rerace married CESDTOT/s ddfm = bw;
random intercept /subject=id type=un;
RUN; 
PROC MIXED data=ACTIVE.step15long method=reml noclprint covtest noitprint; 
class id men rerace(ref="0") married (ref="1");
where intgrpR = 4; 
model  HVLT = reage educlevl men rerace  married CESDTOT/s ddfm = bw;
random intercept /subject=id type=un;
RUN; 
PROC MIXED data=ACTIVE.step15long method=reml noclprint covtest noitprint; 
class id men rerace(ref="0") married (ref="1");
where intgrpR = 4; 
model  AVLT = reage educlevl men rerace  married CESDTOT/s ddfm = bw;
random intercept /subject=id type=un;
RUN; 
PROC MIXED data=ACTIVE.step15long method=reml noclprint covtest noitprint; 
class id men rerace(ref="0") married (ref="1");
where intgrpR = 4; 
model  IMMRAW  = reage educlevl men rerace  married CESDTOT/s ddfm = bw;
random intercept /subject=id type=un;
RUN; 
PROC MIXED data=ACTIVE.step15long method=reml noclprint covtest noitprint; 
class id men rerace(ref="0") married (ref="1");
where intgrpR = 4; 
model  LS_Cor = reage educlevl men rerace  married CESDTOT/s ddfm = bw;
random intercept /subject=id type=un;
RUN; 
PROC MIXED data=ACTIVE.step15long method=reml noclprint covtest noitprint; 
class id men rerace(ref="0") married (ref="1");
where intgrpR = 4; 
model  LT_COR = reage educlevl men rerace  married CESDTOT/s ddfm = bw;
random intercept /subject=id type=un;
RUN; 
PROC MIXED data=ACTIVE.step15long method=reml noclprint covtest noitprint; 
class id men rerace(ref="0") married (ref="1");
where intgrpR = 4; 
model  WS_COR = Sreage educlevl men rerace  married CESDTOT/s ddfm = bw;
random intercept /subject=id type=un;
RUN; 
PROC MIXED data=ACTIVE.step15long method=reml noclprint covtest noitprint; 
class id men rerace(ref="0") married (ref="1");
where intgrpR = 4; 
model  DS_Cor = reage educlevl men rerace  married CESDTOT/s ddfm = bw;
random intercept /subject=id type=un;
RUN; 
PROC MIXED data=ACTIVE.step15long method=reml noclprint covtest noitprint; 
class id men rerace(ref="0") married (ref="1");
where intgrpR = 4; 
model  CRT1 = reage educlevl men rerace  married CESDTOT/s ddfm = bw;
random intercept /subject=id type=un;
RUN; 
PROC MIXED data=ACTIVE.step15long method=reml noclprint covtest noitprint; 
class id men rerace(ref="0") married (ref="1");
where intgrpR = 4; 
model  CRT2 = reage educlevl men rerace  married CESDTOT/s ddfm = bw;
random intercept /subject=id type=un;
RUN; 
PROC MIXED data=ACTIVE.step15long method=reml noclprint covtest noitprint; 
class id men rerace(ref="0") married (ref="1");
where intgrpR = 4; 
model  CRTTotal =reage educlevl men rerace  married CESDTOT/s ddfm = bw;
random intercept /subject=id type=un;
RUN; 
PROC MIXED data=ACTIVE.step15long method=reml noclprint covtest noitprint; 
class id men rerace(ref="0") married (ref="1");
where intgrpR = 4; 
model  UFOV1 = reage educlevl men rerace  married CESDTOT/s ddfm = bw;
random intercept /subject=id type=un;
RUN; 

PROC MIXED data=ACTIVE.step15long method=reml noclprint covtest noitprint; 
class id men rerace(ref="0") married (ref="1");
where intgrpR = 4; 
model  UFOV2 = reage educlevl men rerace  married CESDTOT/s ddfm = bw;
random intercept /subject=id type=un;
RUN; 
PROC MIXED data=ACTIVE.step15long method=reml noclprint covtest noitprint; 
class id men rerace(ref="0") married (ref="1");
where intgrpR = 4; 
model  UFOV3 = reage educlevl men rerace  married CESDTOT/s ddfm = bw;
random intercept /subject=id type=un;
RUN; 
PROC MIXED data=ACTIVE.step15long method=reml noclprint covtest noitprint; 
class id men rerace(ref="0") married (ref="1");
where intgrpR = 4; 
model  UFOV4 = reage educlevl men rerace  married CESDTOT/s ddfm = bw;
random intercept /subject=id type=un;
RUN; 
ods pdf close;
